#!/usr/bin/env php
<?php
/**
 * shell entry
 *
 * @author Alacner Zhang <alacner@gmail.com>
 * @version $Id: app.php 8249 2016-10-27 02:34:08Z alacner $
 */

$_directories = [
	dirname(__FILE__) . '/configs/local/configuration.php',// local first
	dirname(__FILE__) . '/configs/configuration.php',
];

foreach ($_directories as $_file) {
	if (is_file($_file)) {
		require_once $_file;
		break;
	}
}
unset($_directories, $_file);

if (!class_exists('Tii_Version')) {//check framework has already loaded
	trigger_error("The tii framework not loaded correctly", E_USER_ERROR);
}

Tii_Application::run();